# version: '3.8'

services:
  app:
    image: bazaskill-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '${LOCAL_PORT}:${PORT}'
