version: '3.8'

services:
  app:
    image: bazaskill-frontend
    build:
      context: ./
      target: production
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - '${LOCAL_PORT}:${PORT}'
