# version: '3.8'

services:
  app:
    image: bazaskill-frontend
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    restart: always
    ports:
      - '${LOCAL_PORT}:${PORT}'
