export const constants = {
  profile: {
    FETCH_PROFILE: 'FETCH_PROFILE',
  },
  testimonials: {
    ADD_TESTIMONIAL: 'ADD_TESTIMONIAL',
    FETCH_TESTIMONIALS: 'FETCH_TESTIMONIALS',
  },
  specialization: {
    FETCH_SPECIALIZATIONS_WITH_STACK:
      'FETCH_SPECIALIZATIONS_WITH_STACK',
    FETCH_SPECIALIZATIONS: 'FETCH_SPECIALIZATIONS',
  },
  documents: {
    FETCH_DOCUMENTS: 'FETCH_DOCUMENTS',
  },
  partners: {
    ADD_PARTNERS: 'ADD_PARTNERS',
    FETCH_PARTNERS: 'FETCH_PARTNERS',
  },

  hr_applications: {
    FETCH_HRS: 'FETCH_HRS',
    FETCH_HR_BY_ID: 'FETCH_HR_BY_ID',
  },
  partner_applications: {
    FETCH_PARTNER_APPLICATIONS:
      'FETCH_PARTNER_APPLICATIONS',
    FETCH_PARTNER_APPLICATIONS_BY_ID:
      'FETCH_PARTNER_APPLICATIONS_BY_ID',
  },
  contacts: {
    FETCH_CONTACTS: 'FETCH_CONTACTS',
  },
  counters: {
    FETCH_COUNTERS: 'FETCH_COUNTERS',
  },
};
