export const constants = {
  testimonials: {
    ADD_TESTIMONIAL: 'ADD_TESTIMONIAL',
    FETCH_TESTIMONIALS: 'FETCH_TESTIMONIALS',
  },
  specialization: {
    FETCH_SPECIALIZATIONS_WITH_STACK:
      'FETCH_SPECIALIZATIONS_WITH_STACK',
    FETCH_SPECIALIZATIONS: 'FETCH_SPECIALIZATIONS',
  },
  documents: {
    FETCH_DOCUMENTS: 'FETCH_DOCUMENTS',
  },
  partners: {
    ADD_PARTNERS: 'ADD_PARTNERS',
    FETCH_PARTNERS: 'FETCH_PARTNERS',
  },
  contacts: {
    FETCH_CONTACTS: 'FETCH_CONTACTS',
  },
};
