import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import ReduxProvider from '@/redux/ReduxProvider';
import Header from '@/components/main/Header';
import Footer from '@/components/main/Footer';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'BazaSkill',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <ReduxProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <Header />
          </header>
          <main> {children}</main>
          <footer>
            <Footer />
          </footer>
        </body>
      </html>
    </ReduxProvider>
  );
}
