import type { Metadata } from 'next';

import SideBar from '@/components/admin/sidebar/SideBar';
import { WithAuth } from '@/components/admin/WithAuth';

export const metadata: Metadata = {
  title: 'BazaSkill Admin',
  description: 'Generated by create next app',
};

export default function AdminLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <WithAuth>
      <div className="flex bg-graphite text-white">
        <SideBar />
        <div className="flex-1">{children}</div>
      </div>
    </WithAuth>
  );
}
